openapi: 3.1.0
info:
  title: Restaurant API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Testing server
tags:
  - name: Chef
    description: Chef related endpoints
  - name: Item
    description: Item related endpoints
  - name: Combo
    description: Combo related endpoints
paths:
  /chef:
    $ref: paths/chef.yaml
  /item:
    $ref: paths/item.yaml
  /combo:
    $ref: paths/combo.yaml

